// src/component/device/NavigationBar.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { faChevronLeft } from '@fortawesome/free-solid-svg-icons/faChevronLeft';
import { faSquare } from '@fortawesome/free-regular-svg-icons/faSquare';

import { Language, useLanguage } from 'store/Language';
import { Icon } from 'component/common/Icon';
import styles from 'style/device/NavigationBar.scss';
import InKorean from 'image/device/InKorean.svg';
import InEnglish from 'image/device/InEnglish.svg';

/**
 * NavigationBar props.
 */
interface Props {
    showNavigators: boolean;
}

/**
 * Component which represents the (virtual) buttons at the bottom of the phone(tablet).
 */
export const NavigationBar = ({ showNavigators }: Props) => {
    const navigate = useNavigate();
    const { currentLanguage, setLanguage } = useLanguage();

    const nextLanguage: Language = currentLanguage === 'Korean' ? 'English' : 'Korean';
    const languageImage = currentLanguage === 'Korean' ? InKorean : InEnglish;

    return (
        <div className={styles.navigationBar}>
            <div className={styles.cell}>
                <button
                    className={styles.languageButton}
                    style={{
                        backgroundImage: `url(${languageImage})`,
                    }}
                    type={'button'}
                    title={`To ${nextLanguage}`}
                    aria-label={`To ${nextLanguage}`}
                    onClick={() => {
                        setLanguage(nextLanguage);
                    }}
                />
            </div>
            <div className={styles.cell}>
                {showNavigators && (
                    <button
                        className={styles.button}
                        type={'button'}
                        title={'Home'}
                        onClick={() => {
                            navigate('/');
                        }}
                    >
                        <Icon definition={faSquare} />
                    </button>
                )}
            </div>
            <div className={styles.cell}>
                {showNavigators && (
                    <button
                        className={styles.button}
                        type={'button'}
                        title={'Back'}
                        onClick={() => {
                            navigate(-1);
                        }}
                    >
                        <Icon definition={faChevronLeft} />
                    </button>
                )}
            </div>
        </div>
    );
};

// src/component/NavigationBar.svelte
<script lang="ts">
    import { faChevronLeft } from "@fortawesome/free-solid-svg-icons/faChevronLeft";
    import { faSquare } from "@fortawesome/free-regular-svg-icons/faSquare";

    import { currentLanguage, Language } from "store/Language";
    import Icon from "component/Icon.svelte";
    import InKorean from "image/device/InKorean.svg";
    import InEnglish from "image/device/InEnglish.svg";

    export let showNavigators: boolean;

    let nextLanguage: Language;
    let languageImage: string;

    $: nextLanguage = $currentLanguage === "Korean" ? "English" : "Korean";
    $: languageImage = $currentLanguage === "Korean" ? InKorean : InEnglish;
</script>

<div class="navigationBar">
    <div class="cell">
        <button
            class="languageButton"
            style={`background-image: url(${languageImage})`}
            type="button"
            title={`To ${nextLanguage}`}
            aria-label={`To ${nextLanguage}`}
            on:click={() => {
                $currentLanguage = nextLanguage;
            }}
        />
    </div>
    <div class="cell">
        {#if showNavigators}
            <button class="button" type="button" title="Home">
                <Icon definition={faSquare} />
            </button>
        {/if}
    </div>
    <div class="cell">
        {#if showNavigators}
            <button class="button" type="button" title="Back">
                <Icon definition={faChevronLeft} />
            </button>
        {/if}
    </div>
</div>

<style lang="scss">
    @use "./Common";

    .navigationBar {
        display: table;
        width: 100%;
    }

    @mixin baseButton {
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        transition: all 0.1s;

        width: 3rem;
        height: 2.5rem;
        border: none;
        line-height: 2.5rem;
        font-size: 2rem;

        color: Common.$white;
        background-color: transparent;

        &:hover {
            transform: scale(0.8);
        }
    }

    .button {
        @include baseButton();
    }

    .languageButton {
        @include baseButton();

        background-size: auto 2rem;
        background-repeat: no-repeat;
        background-position: center;
    }

    .cell {
        display: table-cell;

        width: 4rem;
        text-align: center;
    }
</style>
