// src/component/device/StatusBar.tsx
import React, { ReactNode } from 'react';
import { faWifi } from '@fortawesome/free-solid-svg-icons/faWifi';
import { faSignal } from '@fortawesome/free-solid-svg-icons/faSignal';
import { faBatteryFull } from '@fortawesome/free-solid-svg-icons/faBatteryFull';

import { Icon } from 'component/common/Icon';
import { AMPM, Hour, Minute, ClockProvider } from 'component/device/Clock';
import styles from 'style/device/StatusBar.scss';

/**
 * Common props for the small components.
 */
interface AreaProps {
    children?: ReactNode;
}

const Left = ({ children = null }: AreaProps) => <div className={styles.left}>{children}</div>;

const Right = ({ children = null }: AreaProps) => <div className={styles.right}>{children}</div>;

const Block = ({ children = null }: AreaProps) => <span className={styles.block}>{children}</span>;

/**
 *
 */
interface StatusBarProps {
    showTime: boolean;
}

export const StatusBar = ({ showTime }: StatusBarProps) => (
    <div className={styles.statusBar}>
        <Left>
            <Block>Hunmin Park</Block>
        </Left>
        <Right>
            <Block>
                <Icon definition={faWifi} />
            </Block>
            <Block>
                <Icon definition={faSignal} />
            </Block>
            <Block>
                <Icon definition={faBatteryFull} />
            </Block>
            {showTime && (
                <Block>
                    <ClockProvider>
                        <Hour />:<Minute /> <AMPM />
                    </ClockProvider>
                </Block>
            )}
        </Right>
    </div>
);

// src/component/StatusBar.svelte
<script lang="ts">
    import { faWifi } from "@fortawesome/free-solid-svg-icons/faWifi";
    import { faSignal } from "@fortawesome/free-solid-svg-icons/faSignal";
    import { faBatteryFull } from "@fortawesome/free-solid-svg-icons/faBatteryFull";

    import Icon from "component/Icon.svelte";
    import { currentAMPM, currentHour, currentMinute } from "store/Time";

    export let showTime: boolean;
</script>

<div class="statusBar">
    <div class="left">
        <div class="block">Hunmin Park</div>
    </div>
    <div class="right">
        <div class="block">
            <Icon definition={faWifi} />
        </div>
        <div class="block">
            <Icon definition={faSignal} />
        </div>
        <div class="block">
            <Icon definition={faBatteryFull} />
        </div>
        {#if showTime}
            <div class="block">
                {$currentHour}:{$currentMinute}
                {$currentAMPM}
            </div>
        {/if}
    </div>
</div>

<style lang="scss">
    @use "./Common";

    .statusBar {
        box-sizing: border-box;
        display: flex;
        flex-direction: row;

        width: 100%;
        height: 2rem;
        padding-left: 0.3rem;
        padding-right: 0.3rem;
        line-height: 2rem;

        color: Common.$white;
    }

    .left {
        height: 100%;
    }

    .right {
        margin-left: auto;
        height: 100%;
    }

    .block {
        display: inline-block;

        margin-left: 0.2rem;
        margin-right: 0.2rem;
    }
</style>
