// src/view/StatusBar.tsx
/** @jsx jsx */

import {jsx} from '@emotion/core';
import {ReactNode} from 'react';
import {faWifi} from '@fortawesome/free-solid-svg-icons/faWifi';
import {faSignal} from '@fortawesome/free-solid-svg-icons/faSignal';
import {faBatteryFull} from '@fortawesome/free-solid-svg-icons/faBatteryFull';
import {Icon} from './Icon';
import {AMPM, Clock, Hour, Minute} from './Clock';

const LeftArea = ({children = {} as ReactNode}) => (
    <div css={{
        float: 'left',
        height: '100%'
    }}>
        {children}
    </div>
);

const RightArea = ({children = {} as ReactNode}) => (
    <div css={{
        float: 'right',
        height: '100%'
    }}>
        {children}
    </div>
);

const Block = ({children = {} as ReactNode}) => (
    <span css={{
        marginLeft: '0.2rem',
        marginRight: '0.2rem'
    }}>
        {children}
    </span>
);

export const StatusBar = ({showTime = true}) => (
    <div css={{
        boxSizing: 'border-box',
        width: '100%',
        height: '2rem',
        paddingLeft: '0.3rem',
        paddingRight: '0.3rem',
        lineHeight: '2rem',
        color: '#ffffff'
    }}>
        <LeftArea>
            <Block>MyPhone</Block>
        </LeftArea>
        <RightArea>
            <Block><Icon definition={faWifi}/></Block>
            <Block><Icon definition={faSignal}/></Block>
            <Block><Icon definition={faBatteryFull}/></Block>
            {showTime && <Block><Clock><Hour/>:<Minute/> <AMPM/></Clock></Block>}
        </RightArea>
    </div>
);

// src/component/StatusBar.svelte
<script lang="ts">
    import { faWifi } from "@fortawesome/free-solid-svg-icons/faWifi";
    import { faSignal } from "@fortawesome/free-solid-svg-icons/faSignal";
    import { faBatteryFull } from "@fortawesome/free-solid-svg-icons/faBatteryFull";

    import Icon from "component/Icon.svelte";
    import { currentAMPM, currentHour, currentMinute } from "store/Time";

    export let showTime: boolean;
</script>

<div class="statusBar">
    <div class="left">
        <div class="block">Hunmin Park</div>
    </div>
    <div class="right">
        <div class="block">
            <Icon definition={faWifi} />
        </div>
        <div class="block">
            <Icon definition={faSignal} />
        </div>
        <div class="block">
            <Icon definition={faBatteryFull} />
        </div>
        {#if showTime}
            <div class="block">
                {$currentHour}:{$currentMinute}
                {$currentAMPM}
            </div>
        {/if}
    </div>
</div>

<style lang="scss">
    @use "./Common";

    .statusBar {
        box-sizing: border-box;
        display: flex;
        flex-direction: row;

        width: 100%;
        height: 2rem;
        padding-left: 0.3rem;
        padding-right: 0.3rem;
        line-height: 2rem;

        color: Common.$white;
    }

    .left {
        height: 100%;
    }

    .right {
        margin-left: auto;
        height: 100%;
    }

    .block {
        display: inline-block;

        margin-left: 0.2rem;
        margin-right: 0.2rem;
    }
</style>
